name:                barbie-demo
version:             0.1.0.0
github:              "koterpillar/barbie-demo"
license:             MIT
author:              "Alexey Kotlyarov"
maintainer:          "a@koterpillar.com"
copyright:           "2021 Alexey Kotlyarov"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/koterpillar/barbie-demo#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  barbie-demo-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - barbies
    - lens
    - text
